### ISSUE TITLE
EP9.4 needs a new URL

### ISSUE THREAD

**Issue by leijerry888** [NREL/docker-energyplus#10]
Download URL in the Dockerfile no longer works for EP9.4 because of the different naming conventions (Ubuntuxx.xx was added to the filename in 9.4).

**Comment by nllong** [comment]
Thanks for catching this. The build script has been updated. 9.4 and 9.5 are now built and on Docker Hub

```
docker pull nrel/energyplus:9.4.0
docker pull nrel/energyplus:9.5.0
```
